product: ocp4
full_name: Red Hat OpenShift Container Platform 4
type: platform

# Maybe this would be changed later to
# also include the k8s content
benchmark_root: "../linux_os/guide"

profiles_root: "./profiles"

pkg_system: "rpm"

init_system: "systemd"
