name: Compare DS
on:
  pull_request_target:
    branches: [ master, 'stabilization*' ]
jobs:
  build-content:
    name: Generate Diff
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install Deps
        run: dnf install -y cmake make openscap-utils python3-pyyaml python3-setuptools python3-jinja2 git python3-deepdiff python3-requests jq python3-pip
      - name: Install deps python
        run: pip install gitpython xmldiff
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      # https://github.com/actions/checkout/issues/766
      - name: Set git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Find forking point
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: echo "::set-output name=FORK_POINT::$(git merge-base origin/$BASE_BRANCH ${{ github.event.pull_request.head.sha }})"
        id: fork_point
      - name: Checkout fork point
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ steps.fork_point.outputs.FORK_POINT }}
          fetch-depth: 0
      - name: Checkout (CTF)
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          repository: mildas/content-test-filtering
          path: ctf
      - name: Detect content changes in the PR
        run: python3 ./ctf/content_test_filtering.py pr --base ${{ steps.fork_point.outputs.FORK_POINT }} --remote_repo ${{ github.server_url }}/${{ github.repository }}  --verbose --rule --output json ${{ github.event.pull_request.number }} > output.json
      - name: Test if there are no content changes
        run: echo "::set-output name=CTF_OUTPUT_SIZE::$(stat --printf="%s" output.json)"
        id: ctf
      - name: Print changes to content detected if any
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        run: cat output.json
      - name: Get product attribute
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        id: product
        uses: notiz-dev/github-action-json-property@a743fcf898fd5a5085f1b58ff4786bc799350997 # release
        with:
          path: 'output.json'
          prop_path: 'product'
      - name: Build product ${{ github.base_ref }} (${{ steps.fork_point.outputs.FORK_POINT }})
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        run: ./build_product ${{steps.product.outputs.prop}} --datastream-only
      - name: Copy built datastream stream to be compared
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        run: cp build/ssg-${{steps.product.outputs.prop}}-ds.xml ssg-${{steps.product.outputs.prop}}-ds.xml
      - name: Checkout
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false
      - name: Build product
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        run: ./build_product ${{steps.product.outputs.prop}} --datastream-only
      - name: Compare datastreams
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        run: utils/compare_ds.py ssg-${{steps.product.outputs.prop}}-ds.xml build/ssg-${{steps.product.outputs.prop}}-ds.xml | tee diff.log
        env:
          PYTHONPATH: ${{ github.workspace }}
      - name: Test if there are datastream changes
        if: ${{ steps.ctf.outputs.CTF_OUTPUT_SIZE != '0' }}
        run: echo "::set-output name=COMPARE_DS_OUTPUT_SIZE::$(stat --printf="%s" diff.log)"
        id: compare_ds
      - name: Print datastream changes if any
        if: ${{ steps.compare_ds.outputs.COMPARE_DS_OUTPUT_SIZE != '0'}}
        run: cat diff.log
      - name: Get diff.log
        if: ${{ steps.compare_ds.outputs.COMPARE_DS_OUTPUT_SIZE != '0'}}
        id: diff
        run: | # set -f to disable any glob expansion that can be triggered in the echo command
          set -f
          body=$(cat diff.log)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=log::${body:0:65000}
          set +f
      - name: Find Comment
        uses: peter-evans/find-comment@d2dae40ed151c634e4189471272b57e76ec19ba8 # v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: This datastream diff is auto generated by the check
      - name: Create or update comment
        if: ${{ steps.compare_ds.outputs.COMPARE_DS_OUTPUT_SIZE != '0' && steps.compare_ds.outputs.COMPARE_DS_OUTPUT_SIZE <= 65000 }}
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This datastream diff is auto generated by the check `Compare DS/Generate Diff`
            <details>
            <summary>Click here to see the full diff</summary>

            ```diff
            ${{ steps.diff.outputs.log }}
            ```

            </details>
          edit-mode: replace
      - name: Create or update a trimmed comment
        if: ${{ steps.compare_ds.outputs.COMPARE_DS_OUTPUT_SIZE > 65000 }}
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae # v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            This datastream diff is auto generated by the check `Compare DS/Generate Diff`.
            Due to the excessive size of the diff, it has been trimmed to fit the 65535-character limit.
            <details>
            <summary>Click here to see the trimmed diff</summary>

            ```diff
            ${{ steps.diff.outputs.log }}

            ... The diff is trimmed here ...
            ```

            </details>
          edit-mode: replace
      - name: Delete existing comment in case new commits trigger no changes in Compare DS tool
        if: ${{ (steps.compare_ds.outputs.COMPARE_DS_OUTPUT_SIZE == '0' || steps.ctf.outputs.CTF_OUTPUT_SIZE == '0') && steps.fc.outputs.comment-id != 0 }}
        uses: jungwinter/comment@fda92dbcb5e7e79cccd55ecb107a8a3d7802a469 # v1
        with:
          type: delete
          comment_id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
